# Common
spring.application.name: lmfr-demo-devfest

# Netty Server
server.port: 7070
server.compression.enabled: true
server.pool.min-threads: 20
server.pool.max-threads: 20
server.pool.idle-timeout: 600000
server.error.whitelabel.enabled: false

# Autoconfiguration exclusions
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.web.reactive.error.ErrorWebFluxAutoConfiguration

# Logging
logging.level.fr.leroymerlin.demodevfest: INFO

# JMX
spring.jmx.enabled: false
spring.application.admin.enabled: false

# Management
management.server.port: 7081
management.server.address: 0.0.0.0
management.server.servlet.context-path: /

# Management endpoints
management.endpoints.web.base-path: /
management.endpoints.enabled-by-default: false
management.endpoints.web.exposure.include:
  - health
  - info
  - env
  - prometheus
  - swagger

management.endpoint.health.enabled: true
management.endpoint.info.enabled: true
management.endpoint.env.enabled: true
management.endpoint.prometheus.enabled: true

# Webflux
spring.webflux.static-path-pattern: /static/**

#spring.resources.cache.cachecontrol.max-age: 900s
#spring.resources.cache.cachecontrol.cache-public: true
spring.resources.cache.period: 900s

# Web client timeout
httpclient.connect-timeout: 500
httpclient.request-timeout: 5000
httpclient.pool.max-size: 200

# Management Info
info.app.name:  @project.name@
info.app.version: @project.version@
info.app.build.number:  @buildNumber@
info.app.build.timestamp:  @timestamp@

# Mongo
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tvshows


tv-show-rating-api:
  baseUrl: http://localhost:8080
  readTimeout: 15000


